/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Vote = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "upvote" | "downvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
};

export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  parentComment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  isReported?: boolean;
  createdAt?: string;
  isDeleted?: boolean;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  originalTitle?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  subreddit?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subreddit";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  isReported?: boolean;
  publishedAt?: string;
  isDeleted?: boolean;
};

export type Subreddit = {
  _id: string;
  _type: "subreddit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  moderator?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  createdAt?: string;
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  email?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  joinedAt?: string;
  isReported?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Vote | Comment | Post | Subreddit | User | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/comment/getCommentById.ts
// Variable: getCommentByIdQuery
// Query: *[_type == "comment" && _id == $commentId][0] {            _id,            content,            createdAt,            "author": author->,            isDeleted        }
export type GetCommentByIdQueryResult = {
  _id: string;
  content: string | null;
  createdAt: string | null;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  isDeleted: boolean | null;
} | null;

// Source: ./sanity/lib/comment/getCommentReplies.ts
// Variable: getCommentRepliesQuery
// Query: *[_type == "comment" && parentComment._ref == $commentId] {            ...,            _id,            content,            createdAt,            "author": author->,            "replies": *[_type == "comment" && parentComment._ref == ^._id],            "votes": {                "upvotes": count(*[_type == "vote" && comment._ref == ^._id && voteType == "upvote"]),                "downvotes": count(*[_type == "vote" && comment._ref == ^._id && voteType == "downvote"]),                "netScore": count(*[_type == "vote" && comment._ref == ^._id && voteType == "upvote"]) - count(*[_type == "vote" && comment._ref == ^._id && voteType == "downvote"]),                "votesStatus": *[_type == "vote" && comment._ref == ^._id && user._ref == $userId][0].voteType            }        } | order(votes.netScore desc)
export type GetCommentRepliesQueryResult = Array<{
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content: string | null;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  parentComment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  isReported?: boolean;
  createdAt: string | null;
  isDeleted?: boolean;
  replies: Array<{
    _id: string;
    _type: "comment";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    content?: string;
    author?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "user";
    };
    post?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "post";
    };
    parentComment?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "comment";
    };
    isReported?: boolean;
    createdAt?: string;
    isDeleted?: boolean;
  }>;
  votes: {
    upvotes: number;
    downvotes: number;
    netScore: number;
    votesStatus: "downvote" | "upvote" | null;
  };
}>;

// Source: ./sanity/lib/post/getPost.ts
// Variable: getAllPostsQuery
// Query: *[_type == "post" && isDeleted == false] {    _type,    _createdAt,    _updatedAt,    _rev,    _id,    title,    "slug": slug.current,    body,    publishedAt,    "author": author->,    "subreddit": subreddit->,    image,    isDeleted} | order(publishedAt desc)
export type GetAllPostsQueryResult = Array<{
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  _id: string;
  title: string | null;
  slug: null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  publishedAt: string | null;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  subreddit: {
    _id: string;
    _type: "subreddit";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    description?: string;
    slug?: Slug;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    moderator?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "user";
    };
    createdAt?: string;
  } | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  isDeleted: boolean | null;
}>;

// Source: ./sanity/lib/post/getPostById.ts
// Variable: getPostByIdQuery
// Query: *[_type == "post" && _id == $postId] {            _id,            title,            "slug": slug.current,            body,            publishedAt,            "author": author->,            "subreddit": subreddit->,            image,            isDeleted        }[0]
export type GetPostByIdQueryResult = {
  _id: string;
  title: string | null;
  slug: null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  publishedAt: string | null;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  subreddit: {
    _id: string;
    _type: "subreddit";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    description?: string;
    slug?: Slug;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    moderator?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "user";
    };
    createdAt?: string;
  } | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  isDeleted: boolean | null;
} | null;

// Source: ./sanity/lib/subreddits/getPostForSubreddit.ts
// Variable: getPostsForSubredditQuery
// Query: *[_type == "post" && subreddit->slug.current == $slug] {      ...,      "slug": slug.current,      "author": author->,      "subreddit": subreddit->,      "category": category->,      "upvotes": count(*[_type == "vote" && post._ref == ^._id && voteType == "upvote"]),      "downvotes": count(*[_type == "vote" && post._ref == ^._id && voteType == "downvote"]),      "netScore": count(*[_type == "vote" && post._ref == ^._id && voteType == "upvote"])                 - count(*[_type == "vote" && post._ref == ^._id && voteType == "downvote"]),      "commentCount": count(*[_type == "comment" && post._ref == ^._id])    } | order(publishedAt desc)
export type GetPostsForSubredditQueryResult = Array<{
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  originalTitle?: string;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  subreddit: {
    _id: string;
    _type: "subreddit";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    description?: string;
    slug?: Slug;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    moderator?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "user";
    };
    createdAt?: string;
  } | null;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  isReported?: boolean;
  publishedAt?: string;
  isDeleted?: boolean;
  slug: null;
  category: null;
  upvotes: number;
  downvotes: number;
  netScore: number;
  commentCount: number;
}>;

// Source: ./sanity/lib/subreddits/getSubredditBySlug.ts
// Variable: getSubredditBySlugQuery
// Query: *[type=="subreddit" && slug.current == $slug[0] ]
export type GetSubredditBySlugQueryResult = Array<never>;

// Source: ./sanity/lib/subreddits/getSubreddits.ts
// Variable: getSubredditsQuery
// Query: *[_type == "subreddit"]{        _id,        title,        "slug": slug.current,        description,        image,        "moderator": moderator->,        createdAt    } | order(createdAt desc)
export type GetSubredditsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  moderator: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  createdAt: string | null;
}>;

// Source: ./sanity/lib/subreddits/searchSubreddits.ts
// Variable: searchSubredditsQuery
// Query: *[_type == "subreddit" && title match $searchTerm + "*"] {            _id,            title,            "slug": slug.current,            description,            image,            "moderator": moderator->,            createdAt        } | order(createdAt desc)
export type SearchSubredditsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  moderator: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  createdAt: string | null;
}>;

// Source: ./sanity/lib/user/getUser.ts
// Variable: getExistingUserQuery
// Query: *[_type == "user" && _id == $id][0]
export type GetExistingUserQueryResult = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  email?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  joinedAt?: string;
  isReported?: boolean;
} | null;

// Source: ./sanity/lib/vote/downvoteComment.ts
// Variable: existingVoteDownvoteCommentQuery
// Query: *[_type == "vote" && comment._ref == $commentId && user._ref == $userId][0]
export type ExistingVoteDownvoteCommentQueryResult = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "downvote" | "upvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
} | null;

// Source: ./sanity/lib/vote/downvotePost.ts
// Variable: existingVoteDownvoteQuery
// Query: *[_type == "vote" && post._ref == $postId && user._ref == $userId][0]
export type ExistingVoteDownvoteQueryResult = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "downvote" | "upvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
} | null;

// Source: ./sanity/lib/vote/getPostComments.ts
// Variable: getPostCommentsQuery
// Query: *[_type == "comment" && post._ref == $postId && !defined(parentComment)] {            ...,            _id,            content,            createdAt,            "author": author->,            "replies": *[_type == "comment" && parentComment._ref == ^._id],            "votes": {                "upvotes": count(*[_type == "vote" && comment._ref == ^._id && voteType == "upvote"]),                "downvotes": count(*[_type == "vote" && comment._ref == ^._id && voteType == "downvote"]),                "netScore": count(*[_type == "vote" && comment._ref == ^._id && voteType == "upvote"]) - count(*[_type == "vote" && comment._ref == ^._id && voteType == "downvote"]),                "votestatus": *[_type == "vote" && comment._ref == ^._id && user._ref == $userId][0].voteType            }        } | order(votes.netScore desc, createdAt desc)
export type GetPostCommentsQueryResult = Array<{
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content: string | null;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  parentComment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  isReported?: boolean;
  createdAt: string | null;
  isDeleted?: boolean;
  replies: Array<{
    _id: string;
    _type: "comment";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    content?: string;
    author?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "user";
    };
    post?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "post";
    };
    parentComment?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "comment";
    };
    isReported?: boolean;
    createdAt?: string;
    isDeleted?: boolean;
  }>;
  votes: {
    upvotes: number;
    downvotes: number;
    netScore: number;
    votestatus: "downvote" | "upvote" | null;
  };
}>;

// Source: ./sanity/lib/vote/getPostVotes.ts
// Variable: getPostVotesQuery
// Query: *[_type == "vote" && post._ref == $postId] {        "upvotes": count(*[_type == "vote" && post._ref == $postId && voteType == "upvote"]),        "downvotes": count(*[_type == "vote" && post._ref == $postId && voteType == "downvote"]),        "netScore": count(*[_type == "vote" && post._ref == $postId && voteType == "upvote"]) - count(*[_type == "vote" && post._ref == $postId && voteType == "downvote"])    }
export type GetPostVotesQueryResult = Array<{
  upvotes: number;
  downvotes: number;
  netScore: number;
}>;

// Source: ./sanity/lib/vote/getUserPostVoteStatus.ts
// Variable: getUserPostVoteStatusQuery
// Query: *[_type == "vote" && post._ref == $postId && user._ref == $userId][0].voteType
export type GetUserPostVoteStatusQueryResult = "downvote" | "upvote" | null;

// Source: ./sanity/lib/vote/upvoteComment.ts
// Variable: existingVoteUpvoteCommentQuery
// Query: *[_type == "vote" && comment._ref == $commentId && user._ref == $userId][0]
export type ExistingVoteUpvoteCommentQueryResult = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "downvote" | "upvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
} | null;

// Source: ./sanity/lib/vote/upvotePost.ts
// Variable: existingVoteUpvoteQuery
// Query: *[_type == "vote" && post._ref == $postId && user._ref == $userId][0]
export type ExistingVoteUpvoteQueryResult = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "downvote" | "upvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n        *[_type == \"comment\" && _id == $commentId][0] {\n            _id,\n            content,\n            createdAt,\n            \"author\": author->,\n            isDeleted\n        }\n    ": GetCommentByIdQueryResult;
    "*[_type == \"comment\" && parentComment._ref == $commentId] {\n            ...,\n            _id,\n            content,\n            createdAt,\n            \"author\": author->,\n            \"replies\": *[_type == \"comment\" && parentComment._ref == ^._id],\n            \"votes\": {\n                \"upvotes\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"upvote\"]),\n                \"downvotes\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"downvote\"]),\n                \"netScore\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"upvote\"]) - count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"downvote\"]),\n                \"votesStatus\": *[_type == \"vote\" && comment._ref == ^._id && user._ref == $userId][0].voteType\n            }\n        } | order(votes.netScore desc)": GetCommentRepliesQueryResult;
    "*[_type == \"post\" && isDeleted == false] {\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    _id,\n    title,\n    \"slug\": slug.current,\n    body,\n    publishedAt,\n    \"author\": author->,\n    \"subreddit\": subreddit->,\n    image,\n    isDeleted\n} | order(publishedAt desc)": GetAllPostsQueryResult;
    "\n        *[_type == \"post\" && _id == $postId] {\n            _id,\n            title,\n            \"slug\": slug.current,\n            body,\n            publishedAt,\n            \"author\": author->,\n            \"subreddit\": subreddit->,\n            image,\n            isDeleted\n        }[0]\n    ": GetPostByIdQueryResult;
    "\n    *[_type == \"post\" && subreddit->slug.current == $slug] {\n      ...,\n      \"slug\": slug.current,\n      \"author\": author->,\n      \"subreddit\": subreddit->,\n      \"category\": category->,\n      \"upvotes\": count(*[_type == \"vote\" && post._ref == ^._id && voteType == \"upvote\"]),\n      \"downvotes\": count(*[_type == \"vote\" && post._ref == ^._id && voteType == \"downvote\"]),\n      \"netScore\": count(*[_type == \"vote\" && post._ref == ^._id && voteType == \"upvote\"]) \n                - count(*[_type == \"vote\" && post._ref == ^._id && voteType == \"downvote\"]),\n      \"commentCount\": count(*[_type == \"comment\" && post._ref == ^._id])\n    } | order(publishedAt desc)\n  ": GetPostsForSubredditQueryResult;
    "\n    *[type==\"subreddit\" && slug.current == $slug[0] ]": GetSubredditBySlugQueryResult;
    "*[_type == \"subreddit\"]{\n        _id,\n        title,\n        \"slug\": slug.current,\n        description,\n        image,\n        \"moderator\": moderator->,\n        createdAt\n    } | order(createdAt desc)": GetSubredditsQueryResult;
    "\n        *[_type == \"subreddit\" && title match $searchTerm + \"*\"] {\n            _id,\n            title,\n            \"slug\": slug.current,\n            description,\n            image,\n            \"moderator\": moderator->,\n            createdAt\n        } | order(createdAt desc)\n    ": SearchSubredditsQueryResult;
    "*[_type == \"user\" && _id == $id][0]": GetExistingUserQueryResult;
    "\n        *[_type == \"vote\" && comment._ref == $commentId && user._ref == $userId][0]\n    ": ExistingVoteDownvoteCommentQueryResult;
    "\n        *[_type == \"vote\" && post._ref == $postId && user._ref == $userId][0]\n    ": ExistingVoteDownvoteQueryResult | ExistingVoteUpvoteQueryResult;
    "*[_type == \"comment\" && post._ref == $postId && !defined(parentComment)] {\n            ...,\n            _id,\n            content,\n            createdAt,\n            \"author\": author->,\n            \"replies\": *[_type == \"comment\" && parentComment._ref == ^._id],\n            \"votes\": {\n                \"upvotes\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"upvote\"]),\n                \"downvotes\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"downvote\"]),\n                \"netScore\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"upvote\"]) - count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"downvote\"]),\n                \"votestatus\": *[_type == \"vote\" && comment._ref == ^._id && user._ref == $userId][0].voteType\n            }\n        } | order(votes.netScore desc, createdAt desc)": GetPostCommentsQueryResult;
    "*[_type == \"vote\" && post._ref == $postId] {\n        \"upvotes\": count(*[_type == \"vote\" && post._ref == $postId && voteType == \"upvote\"]),\n        \"downvotes\": count(*[_type == \"vote\" && post._ref == $postId && voteType == \"downvote\"]),\n        \"netScore\": count(*[_type == \"vote\" && post._ref == $postId && voteType == \"upvote\"]) - count(*[_type == \"vote\" && post._ref == $postId && voteType == \"downvote\"])\n    }": GetPostVotesQueryResult;
    "*[_type == \"vote\" && post._ref == $postId && user._ref == $userId][0].voteType": GetUserPostVoteStatusQueryResult;
    "*[_type == \"vote\" && comment._ref == $commentId && user._ref == $userId][0]": ExistingVoteUpvoteCommentQueryResult;
  }
}
